spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

server:
  servlet:
    context-path: /api

logging:
  level:
    ci.hardwork.authservice: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/auth-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

app:
  security:
    bcrypt-rounds: 15