spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_ai_db_dev
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

logging:
  level:
    ci.hardwork.chatai: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.security: DEBUG

app:
  ai:
    conversation:
      max-history: 20  # Smaller history for dev
      auto-cleanup-days: 7
  rate-limit:
    requests-per-minute: 120  # More lenient for dev
    burst-capacity: 20