name: CI - Spring Boot Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupère ton code
      - name: Checkout
        uses: actions/checkout@v4

      # Installe Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Build + tests
      - name: Build with Maven
        run: mvn -B -ntp clean verify

      # Sauvegarde ton JAR comme artefact téléchargeable
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar
